version = 1
exclude_patterns = []
test_patterns = []

[[analyzers]]
  name = "java"
  enabled = true

  [analyzers.meta]
    runtime_version = "9"

[[analyzers]]
  name = "test-coverage"
  enabled = true

[[transformers]]
  name = "google-java-format"
  enabled = true
